"""add Department

Revision ID: 844e8883278b
Revises: 776d91bc9a91
Create Date: 2024-01-25 16:19:14.533941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844e8883278b'
down_revision = '776d91bc9a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
